
#     ___    __                _ __  __
#    /   |  / /___ ___________(_) /_/ /___  __
#   / /| | / / __ `/ ___/ ___/ / __/ __/ / / /
#  / ___ |/ / /_/ / /__/ /  / / /_/ /_/ /_/ /
# /_/  |_/_/\__,_/\___/_/  /_/\__/\__/\__, /
#                                    /____/

# ALACRITTY CONFIG (~/.config/alacritty/alacritty.yml)
# --------------------------------------------------------------------------

# Terminal Emulator Settings
window:
  padding:
    x: 15
    y: 15
  scrolling:
    history: 15

# Setting zsh as the default shell
shell:
    program: /bin/zsh

# Font
font:
  normal:
    family: Fira Code
    style: Medium

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  bold_italic:
    family: Fira Code
    style: Bold Italic

  size: 10

# Bell
bell:
  animation: EaseOutSine
  duration: 0
  color: '#d8d8d8'

# Colors
colors:
  # Default colors
  primary:
    background: '#181818'
    foreground: '#d8d8d8'

  # Normal colors
  normal:
    black:   '#383838'
    red:     '#AB4642'
    green:   '#A1B56C'
    yellow:  '#F7CA88'
    blue:    '#7CAFC2'
    magenta: '#BA8BAF'
    cyan:    '#86C1B9'
    white:   '#D8D8D8'

  # Bright colors
  bright:
    black:   '#282828'
    red:     '#702E2B'
    green:   '#6A7747'
    yellow:  '#A38559'
    blue:    '#517380'
    magenta: '#7A5B73'
    cyan:    '#587F7A'
    white:   '#8E8E8E'


# Apply Settings without relaunching
live_config_reload: true
